"""
Order flow recorder — persists live data to Parquet for replay, journal, and analysis.

Four data layers, each with distinct semantics:

  RAW:
    1. tape_YYYY-MM-DD.parquet     — raw trade stream (every fill from WS)

  DERIVED (aggregated from raw):
    2. cvd_YYYY-MM-DD.parquet      — sampled CVD snapshots (periodic, not per-tick)
    3. footprint_YYYY-MM-DD.parquet — aggregated footprint buckets (price×time volume matrix)

  SIGNALS (generated by signal engine):
    4. signals_YYYY-MM-DD.parquet  — detected setups with entry/sl/tp/confidence/outcome

Data accumulates continuously in memory.
Flush to Parquet occurs every `flush_interval` seconds (default 30).

Usage:
    recorder = OrderFlowRecorder()
    recorder.start()

    # from WS trade handler — every fill
    recorder.on_trade(ts, px, sz, side, tid)

    # from periodic sampler — every N seconds
    recorder.snapshot_cvd(cvd_value)

    # from aggregator — at bucket close
    recorder.snapshot_footprint(time_bucket, levels)

    # from signal engine — on detected setup
    recorder.log_signal(signal_type="cvd_divergence", side="long", ...)
"""

import time
import threading
import logging
from pathlib import Path
from datetime import datetime, timezone
from typing import Any

import polars as pl

logger = logging.getLogger(__name__)

DEFAULT_DIR = Path(__file__).parent.parent.parent / "data" / "orderflow"


class OrderFlowRecorder:
    def __init__(self, data_dir: Path | None = None, flush_interval: int = 30):
        self.data_dir = data_dir or DEFAULT_DIR
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self.flush_interval = flush_interval

        self._lock = threading.Lock()
        self._trades: list[dict] = []
        self._cvd: list[dict] = []
        self._footprint: list[dict] = []
        self._signals: list[dict] = []

        self._flush_thread: threading.Thread | None = None
        self._running = False

    def start(self):
        """Start background thread that flushes accumulated data to Parquet."""
        self._running = True
        self._flush_thread = threading.Thread(target=self._flush_loop, daemon=True)
        self._flush_thread.start()
        logger.info(
            "OrderFlowRecorder: flush every %ds → %s",
            self.flush_interval,
            self.data_dir,
        )

    def stop(self):
        self._running = False
        self.flush()

    def _flush_loop(self):
        while self._running:
            time.sleep(self.flush_interval)
            try:
                self.flush()
            except Exception as e:
                logger.error("Flush failed: %s", e)

    # ── Layer 1: Raw Trade Stream ─────────────────────────────────────

    def on_trade(self, ts: int, px: float, sz: float, side: str, tid: int = 0):
        """Record a single fill from the WebSocket trade feed."""
        with self._lock:
            self._trades.append({
                "ts": ts,
                "px": px,
                "sz": sz,
                "side": side,
                "tid": tid,
                "notional": round(px * sz, 2),
            })

    # ── Layer 2: Sampled CVD Snapshots ────────────────────────────────

    def snapshot_cvd(self, cvd_value: float, ts: int | None = None):
        """
        Periodic CVD sample (not per-tick — sampled every N seconds).
        Resolution depends on caller frequency, typically 5s.
        """
        if ts is None:
            ts = int(time.time() * 1000)
        with self._lock:
            self._cvd.append({"ts": ts, "cvd": cvd_value})

    # ── Layer 3: Derived Footprint Buckets ────────────────────────────

    def snapshot_footprint(self, time_bucket: int, levels: dict):
        """
        Save an aggregated footprint bucket (price×time volume matrix).
        This is a *derived* structure built from raw trades, not raw data itself.
        levels: {price: {buy_vol, sell_vol, delta, buy_count, sell_count}}
        """
        with self._lock:
            for px_str, data in levels.items():
                self._footprint.append({
                    "time_bucket": time_bucket,
                    "px": float(px_str),
                    "buy_vol": data.get("buy_vol", 0),
                    "sell_vol": data.get("sell_vol", 0),
                    "delta": data.get("delta", 0),
                    "buy_count": data.get("buy_count", 0),
                    "sell_count": data.get("sell_count", 0),
                })

    # ── Layer 4: Signal Log ───────────────────────────────────────────

    def log_signal(
        self,
        signal_type: str,
        side: str,
        entry: float,
        sl: float,
        tp: float,
        confidence: float = 0.0,
        ts: int | None = None,
        meta: dict[str, Any] | None = None,
    ):
        """
        Record a detected setup from the signal engine.
        Outcome can be filled later via update_signal_outcome().
        """
        if ts is None:
            ts = int(time.time() * 1000)
        row: dict[str, Any] = {
            "ts": ts,
            "signal_type": signal_type,
            "side": side,
            "entry": entry,
            "sl": sl,
            "tp": tp,
            "confidence": round(confidence, 4),
            "r_reward": round(abs(tp - entry) / abs(entry - sl), 2) if abs(entry - sl) > 0 else 0.0,
            "outcome": "pending",
        }
        if meta:
            for k, v in meta.items():
                row[f"meta_{k}"] = v
        with self._lock:
            self._signals.append(row)

    def update_signal_outcome(
        self, ts: int, outcome: str, pnl: float = 0.0
    ):
        """Mark a signal's outcome after resolution (win/loss/scratch/timeout)."""
        with self._lock:
            for sig in reversed(self._signals):
                if sig["ts"] == ts:
                    sig["outcome"] = outcome
                    sig["pnl"] = pnl
                    return True
        return False

    # ── Flush to Parquet ──────────────────────────────────────────────

    def flush(self):
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

        with self._lock:
            trades = self._trades.copy()
            cvd = self._cvd.copy()
            footprint = self._footprint.copy()
            signals = self._signals.copy()
            self._trades.clear()
            self._cvd.clear()
            self._footprint.clear()
            self._signals.clear()

        if trades:
            self._append_parquet(trades, f"tape_{today}.parquet")
            logger.info("Flushed %d raw trades → tape_%s.parquet", len(trades), today)

        if cvd:
            self._append_parquet(cvd, f"cvd_{today}.parquet")

        if footprint:
            self._append_parquet(footprint, f"footprint_{today}.parquet")

        if signals:
            self._append_parquet(signals, f"signals_{today}.parquet")
            logger.info("Flushed %d signals → signals_%s.parquet", len(signals), today)

    def _append_parquet(self, rows: list[dict], filename: str):
        path = self.data_dir / filename
        new_df = pl.DataFrame(rows)

        if path.exists():
            existing = pl.read_parquet(path)
            combined = pl.concat([existing, new_df], how="diagonal")
        else:
            combined = new_df

        combined.write_parquet(path)

    # ── Read back ─────────────────────────────────────────────────────

    def _read(self, prefix: str, date: str | None = None) -> pl.DataFrame:
        if date is None:
            date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        path = self.data_dir / f"{prefix}_{date}.parquet"
        if not path.exists():
            return pl.DataFrame()
        return pl.read_parquet(path)

    def read_tape(self, date: str | None = None) -> pl.DataFrame:
        """Raw trade stream for the given date."""
        return self._read("tape", date)

    def read_cvd(self, date: str | None = None) -> pl.DataFrame:
        """Sampled CVD snapshots for the given date."""
        return self._read("cvd", date)

    def read_footprint(self, date: str | None = None) -> pl.DataFrame:
        """Derived footprint buckets for the given date."""
        return self._read("footprint", date)

    def read_signals(self, date: str | None = None) -> pl.DataFrame:
        """Detected signals for the given date."""
        return self._read("signals", date)

    def read_signals_range(self, start: str, end: str) -> pl.DataFrame:
        """Read and concatenate signals across a date range (YYYY-MM-DD)."""
        from datetime import timedelta
        frames = []
        current = datetime.strptime(start, "%Y-%m-%d")
        end_dt = datetime.strptime(end, "%Y-%m-%d")
        while current <= end_dt:
            df = self.read_signals(current.strftime("%Y-%m-%d"))
            if not df.is_empty():
                frames.append(df)
            current += timedelta(days=1)
        if not frames:
            return pl.DataFrame()
        return pl.concat(frames, how="diagonal")

    # ── Stats ─────────────────────────────────────────────────────────

    def stats(self) -> dict:
        files = list(self.data_dir.glob("*.parquet"))
        total_size = sum(f.stat().st_size for f in files)
        with self._lock:
            return {
                "pending_trades": len(self._trades),
                "pending_cvd_snapshots": len(self._cvd),
                "pending_footprint_buckets": len(self._footprint),
                "pending_signals": len(self._signals),
                "files_on_disk": len(files),
                "total_size_mb": round(total_size / 1e6, 2),
                "data_dir": str(self.data_dir),
            }
